spring.application.name=ehr-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ehrdb?useSSL=false&serverTimezone=Asia/Colombo
spring.datasource.username=root
spring.datasource.password=Huawei@123
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.default-property-inclusion=non_null
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE